### ISSUE TITLE
The requested module 'flast' does not provide an export named 'utils'

### ISSUE THREAD

**Issue by Ogyeet10** [PerimeterX/restringer#120]
## Description
When running any `restringer` command (including `restringer -h`), the command fails with a SyntaxError indicating that the 'flast' module does not provide an export named 'utils'. This issue should affect any system with Node.js v20.13.0 and a fresh global installation of restringer.

## Error Message
```
(node:12538) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
SyntaxError: The requested module 'flast' does not provide an export named 'utils'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```
### Reproduction Environment
- Node.js version: v20.13.0 (fresh installation)
- NPM version: 10.5.2
- Restringer version: 2.0.0
- Installation method: Fresh `npm install -g restringer`

### Test System Details (where reproduced)
- Platform: GitHub Codespace
- OS: Ubuntu 20.04.6 LTS x86_64

## Steps to Reproduce
1. Start with a fresh installation of Node.js v20.13.0
2. Install restringer globally: `npm install -g restringer`
3. Run any restringer command (e.g., `restringer -h`, `restringer --output`, etc.)

## Expected Behavior
The command should execute its intended function (display help information,  deobfuscate, etc.).

## Actual Behavior
All commands fail with the same SyntaxError related to missing exports from the 'flast' dependency. 

The error occurs in `[node_modules path]/restringer/src/restringer.js` line 2, specifically when trying to import the `utils` export from 'flast'.

**Comment by BenBaryoPX** [comment]
Thanks for raising this issue!
This should now be fixed in v2.0.2
Please re-open the ticket if the issue persists
