### ISSUE TITLE
Website doesn't modify/deobfuscate code

### ISSUE THREAD

**Issue by j4k0xb** [PerimeterX/restringer#21]
![image](https://user-images.githubusercontent.com/55899582/196052526-99133419-f8e5-49a2-aa58-95c6bdcfa21a.png)
![image](https://user-images.githubusercontent.com/55899582/196052538-15d07347-79a9-41e7-bb5a-50ae5a9d9de6.png)

I also tried it with some other examples from the tests but it didn't deobfuscate them either on the website

**Comment by BenBaryoPX** [comment]
I've fixed the issue by updating the version on the site to the latest REstringer version.
Thank you for taking the time to open an issue to point it out! :)

**Comment by j4k0xb** [comment]
Now every request times out.. please fix it again

**Comment by BenBaryoPX** [comment]
I've restarted the service. Thanks again for bringing this to my attention.
