### ISSUE TITLE
Stop at a certain cycle

### ISSUE THREAD

**Issue by j9a12c20k** [PerimeterX/restringer#26]
Hello,

I just found this npm package and am currently using it for a very heavily obfuscated file. It does a lot of replacing, which I need from what I saw in the terminal log. It seems that REstringer stops after a particular cycle. Is it possible to write the partially decrypted code REstringer before it 'hangs'? For reference, it suspends at Cycle 5 shortly after doing some changes.

Thank you

**Comment by BenBaryoPX** [comment]
Hi @j9a12c20k, thanks for reaching out.
I've also noticed this behavior and I think this is a good idea for a feature.
Most of the implementation is already there so I don't think it's a lot of work.

I'm thinking of adding a method to limit the number of cycles to run, and exposing it as a command line option.
Is that what you had in mind?

**Comment by j9a12c20k** [comment]
Yep! that would definitely help with a lot of mundane tasks

**Comment by BenBaryoPX** [comment]
I've merged the feature - check it out:
`restringer obfuscated.js -m 6`
also
`restringer obfuscated.js --max-iterations 6`
