### ISSUE TITLE
replaceFunctionShellsWithWrappedValue bug when function isn't called

### ISSUE THREAD

**Issue by j4k0xb** [PerimeterX/restringer#45]
```js
function fn() {
  return 0;
}
const obj = { key: fn };
```
output:
```js
function fn() {
  return 0;
}
const obj = { 0 };
```
It shouldn't inline the function since it isn't being called
In case of `console.log(fn);` it even replaces the whole statement with `0;`

**Comment by BenBaryoPX** [comment]
Welp, that's not good! Thanks for reporting, I'll get on it.

**Comment by j4k0xb** [comment]
I can do it, should be a quick fix

**Comment by BenBaryoPX** [comment]
Much appreciated

**Comment by BenBaryoPX** [comment]
Good catch and great job resolving it! I really appreciate your attention to the project's standards!
Thanks!
