### ISSUE TITLE
File output doen't work (as expected)

### ISSUE THREAD

**Issue by Davincible** [PerimeterX/restringer#47]
Currently the only way to write to file is with only `-o`, to use the default output name. `-o myfile.js` `--output myfile.js` `--output=myfile.js` doesn't work.

Also the initial .js suffix remains in the default file name

**Comment by BenBaryoPX** [comment]
I didn't write the `=` usability when parsing the arguments - I'll add it, thanks for pointing it out :)
Keeping the initial `.js` extension is actually how I would like it to be as it keeps the original and deobfuscated version grouped in a GUI and helps when running shell scripts that use the original filename so there's no need to replace the extension.

**Comment by Davincible** [comment]
> there's no need to replace the extension

I mean that now the output is `webmssdk.js-deob.js`, I assumed it would've been `webmssdk-deob.js`. But if it's intentional all good.
