### ISSUE TITLE
Request - module to clean up maths expressions

### ISSUE THREAD

**Issue by Davincible** [PerimeterX/restringer#48]
```js
            _0x64be2f = _0x3b3d74[-429 + -737 * 1 + 1167];
            _0x1f0a2f = _0x3b3d74[-2123 + 3745 + -270 * 6];
            _0x72bb57 = _0x3b3d74[-1 * 275 + 4833 + 1 * -4555];
            _0x3e1a62 = _0x3b3d74[-2684 + -5927 + -1 * -8615];
            _0x3b3d74 = _0x3b3d74[-3175 + 8206 + -5031];
```

**Comment by j4k0xb** [comment]
that already exists
![image](https://user-images.githubusercontent.com/55899582/206886985-961c78ce-09a4-4478-8e34-05c06f14b7cc.png)

**Comment by Davincible** [comment]
Hm, I ran it on [this](https://sf16-secsdk.ttwstatic.com/obj/rc-web-sdk-gcs/webmssdk/1.0.0.460/webmssdk.js) file but it didn't work

**Comment by j4k0xb** [comment]
seems to be because of this error
> [-] Unable to apply changes to AST: Error: Script is broken.

**Comment by Davincible** [comment]
I got a lot of those, any idea why? Script itself isn't broken

**Comment by j4k0xb** [comment]
but it is being broken by one of the deobfuscations
```
[+] replaceEvalCallsWithLiteralContent committed 2 new changes!
src/modules/utils/logger.js:17
		[+] Replacing	eval("require('crypto');")                                  	--with--	require('crypto');
src/modules/utils/logger.js:17
		[+] Replacing	eval("require('buffer')['Buffer'];")                        	--with--	require('buffer')['Buffer'];
```
before:
```js
var _0x45294f = eval("require('crypto');"), _0x85d24 = eval("require('buffer')['Buffer'];"), _0x1de599 = function (_0x564aa0) {
```
after:
```js
var _0x45294f = require('crypto');, _0x85d24 = require('buffer')['Buffer'];, _0x1de599 = function (_0x564aa0) {
```

**Comment by Davincible** [comment]
Ahh I see. Thanks for the info

**Comment by Davincible** [comment]
Thanks a lot for the quick fix. 

If I now run it's not failing on the same thing, but I get a lot of `[-] Error in _evalInVm: ReferenceError: _0x5cbf7e is not defined`, any clue what that might be related to?
