### ISSUE TITLE
dont know if this is normal or what?

### ISSUE THREAD

**Issue by xmoufyy** [PerimeterX/restringer#83]
so i always get stuck on  resolveAugmentedFunctionWrappedArrayReplacements for hours on end and accidently closed it once but also my file is 48000kb and very long so i wanna know if its normal or a performance issue

**Comment by xmoufyy** [comment]
the memor usage also stays the same while its doing it and slowly goes down every few minutes

**Comment by ctrl-escp** [comment]
Yeah it seems this method causes trouble sometimes. It should definitely be refactored to avoid this issue.
You can try and comment it out from the `restringer.js` file [(line 136)](https://github.com/PerimeterX/restringer/blob/main/src/restringer.js#L136) to avoid the issue for now

**Comment by xmoufyy** [comment]
> Yeah it seems this method causes trouble sometimes. It should definitely be refactored to avoid this issue. You can try and comment it out from the `restringer.js` file [(line 136)](https://github.com/PerimeterX/restringer/blob/main/src/restringer.js#L136) to avoid the issue for now

yeah thanks it worked but also got this is this normal or what sorry for the questions im new to this 
![image](https://github.com/PerimeterX/restringer/assets/128886647/bf7dc89e-315b-4e67-93ae-67ee2098fb1b)

**Comment by xmoufyy** [comment]
there is a lot

**Comment by BenBaryoPX** [comment]
What you're seeing is normal when showing log level DEBUG. You can ignore it since it just means a piece of code could not be evaluated. That happens a lot and is expected behavior whether anything was deobfuscated or not.
